# Generated by Django 4.2.18 on 2026-02-23 01:52

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Scholarships',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('scholarship_details', models.TextField()),
                ('deadline', models.DateField(blank=True, null=True)),
                ('contact_name', models.CharField(max_length=255)),
                ('contact_phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('contact_email', models.EmailField(max_length=254)),
                ('application_link', models.URLField(max_length=500)),
            ],
        ),
    ]
