# Generated by Django 4.2.18 on 2026-02-23 01:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scholarships', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Scholarships',
            new_name='Scholarship',
        ),
    ]
