# Generated by Django 4.2.18 on 2026-02-23 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('is_alumni', models.BooleanField(default=False, verbose_name='Are you an Alumnus?')),
                ('year_group', models.IntegerField(blank=True, null=True, verbose_name='Graduation Year (Alumni only)')),
            ],
        ),
    ]
